from __future__ import annotations

FILE_MAGIC = b"CLCOL001"
BLOCK_MAGIC = b"BLK1"
FOOTER_MAGIC = b"CLFTR001"

FORMAT_VERSION = 1
FILE_HEADER_SIZE = 64
BLOCK_HEADER_SIZE = 64
FOOTER_SIZE = 64
INDEX_ENTRY_SIZE = 64

DEFAULT_TARGET_BLOCK_BYTES = 65536
DEFAULT_MIN_ROWS = 512
DEFAULT_MAX_ROWS = 65536

FLAG_NULLABLE = 1
